name: Test flake

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v3
      - run: nix develop -c just check
      - run: nix develop -c just cache-inputs
      - run: nix develop -c just cache-shell

  build:
    needs:
      - check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - default
          - neovim
    steps:
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v4
      - run: nix develop -c just cache-build "${{ matrix.profile }}"
