name: Test flake

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHIX_BINARY_CACHE: altf4llc-os

jobs:
  check:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: nix develop -c just check

  package:
    needs:
      - check
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        profile:
          - default
          - neovim
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: nix develop -c just package "${{ matrix.profile }}"
