name: Test flake

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHIX_BINARY_CACHE: altf4llc-os

jobs:
  check:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          authtoken: ${{ secrets.cachix_auth_token }}
          name: ${{ env.cachix_binary_cache }}
      - uses: actions/checkout@v4
      - run: nix develop -c just check

  build:
    needs:
      - check
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        profile:
          - default
          - neovim
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          authtoken: ${{ secrets.cachix_auth_token }}
          name: ${{ env.cachix_binary_cache }}
      - uses: actions/checkout@v4
      - run: nix develop -c just build "${{ matrix.profile }}"
